### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by TusharSharmaIN** [imtusharsharma/RainingFractalTree#1]
Add Gifs, Images or any media for the project.

**Comment by Sukhija-Aniket** [comment]
Can you assign me this issue I would  like to work on it.

**Comment by DeepShikhaIN** [comment]
Hey @TusharSharmaIN,
I have updated README file, please check. [PR](https://github.com/TusharSharmaIN/RainingFractalTree/pull/2)

**Comment by Sukhija-Aniket** [comment]
I was about to commit🥲.

**Comment by TusharSharmaIN** [comment]
Don't worry @Sukhija-Aniket, you can fetch from upstream and commit again adding a more detailed readme.
